package:
  name: smirnoff99frosst
  version: "1.1.0"

source:
  git_url: https://github.com/openforcefield/smirnoff99frosst.git
  git_tag: 1.1.0

build:
  number: 2
  noarch: python
  entry_points:
    - smirnoff99frosst = smirnoff99frosst.smirnoff99frosst:main
  skip: True  # [win32 or py27 or py35]
  script:
    - ${PYTHON}  -m pip install .

extra:
 upload: main
# include_omnia_label: rc

about:
  home: https://github.com/openforcefield/smirnoff99frosst
  license: CC-BY
  summary: 'The smirnoff99Frosst line of force fields'

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - smirnoff99frosst
